### ISSUE TITLE
Please specify rust-version

### ISSUE THREAD

**Issue by kornelski** [tuffy/bitstream-io#21]
This crate uses just-released Rust 1.79 feature without specifying rust-version in Cargo.toml. This makes older Rust confuse users complaining about experimental features and barfing compilation errors, instead of clearly communicating that their Rust is too old.

**Comment by 9mm** [comment]
Now this says I have to use 1.79 and can't even use 1.78... is this the expected behavior?

**Comment by kornelski** [comment]
Yes. You've used inline const{} syntax added in Rust 1.79, and unsupported in earlier versions.

**Comment by 9mm** [comment]
Im new to rust and just included the `image` crate. I dont believe I use inline consts but... i suppose it doesnt matter because I upgraded rust to 1.79

**Comment by kornelski** [comment]
Oh, nevermind. I've noticed the problem was only in 2.4.0, and 2.4.1 has rust-version.
